# Generated by Django 4.2.1 on 2023-05-08 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300)),
                ('country', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('members', models.CharField(blank=True)),
                ('image', models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True)),
                ('year', models.CharField(blank=True)),
                ('color', models.CharField(blank=True)),
                ('tracklist', models.CharField(blank=True)),
                ('country', models.CharField(blank=True)),
                ('genre', models.CharField(blank=True)),
                ('image', models.CharField(blank=True)),
                ('on_sale', models.BooleanField(blank=True, null=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='bands.band')),
                ('variants', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bands.album')),
            ],
        ),
    ]
